# Generated by Django 4.0.3 on 2022-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_age_group_product_color_product_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.FloatField(default=4),
        ),
    ]
